name: mac-hdf5-build

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened]
  release:
    types: [created]

jobs:
  build:
    runs-on: macos-latest

    env:
      HDF5_INSTALL_DIR: /opt/homebrew/Cellar/hdf5@1.10/1.10.11/
      OUTPUT_FILE: hdf5kdb-mac.tgz
      QHOME: ${{ github.workspace }}/qhome

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install hdf5 lib
        run: brew install hdf5@1.10

      - name: find
        run: find /opt/homebrew/Cellar/ -name hdf5.h -print

      - name: Build
        run: |
          mkdir cmake && cd cmake && cmake .. -DCMAKE_POLICY_VERSION_MINIMUM=3.5 -DCMAKE_BUILD_TYPE=Release && cmake --build . --target install && cd .. && tar  -zcvf "$OUTPUT_FILE" -C cmake/hdf5 .

      - name: Upload workflow artifact
        uses: actions/upload-artifact@v6
        with:
          name: hdf5-mac
          path: ${{ env.OUTPUT_FILE }}
          retention-days: 1

  release:
    needs: build
    permissions:
      contents: write
    uses: ./.github/workflows/release-assets.yml
